# Generated by Django 4.2.3 on 2023-07-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
