# Generated by Django 4.2.3 on 2023-07-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.CharField(default='', max_length=400),
        ),
    ]
